server:
  port: 8080

spring:
  application:
    name: real-estate-search

  datasource:
    url: jdbc:postgresql://localhost:5432/real_estate_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # change to validate in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  elasticsearch:
    rest:
      uris: http://localhost:9200

